# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Best Beer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Best Beer
  pod 'ReachabilitySwift'
  pod 'RealmSwift'
  pod 'ObjectMapper'

  
  target 'Best BeerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Best BeerUITests' do
    # Pods for testing
  end

end
